### ISSUE TITLE
【相談】サーバーの OS を CoreOS + Docker ベースにしたい

### ISSUE THREAD

**Issue by KEINOS** [Qithub-BOT/Qithub-ORG#176]
## 相談

サーバーの OS を CentOS から CoreOS に変更して、各種機能の実装を Docker ベースにしたい。

## 自分の案

現在のサーバーの構成は煩雑で、仕様も複雑な気がします。開発がしづらいと感じます。

そもそも現在のサーバーは Wordpress を動かしていた環境を引き継いだため、CentOS + Kusanagi + HHVM ベースで動かしていました。しかし、Wordpress 使っていない＋ HHVM 互換を考えるのが面倒 ＋ HHVM が PHP の扱いを止めなどの理由もあり、普通に PHP7 で動かしたいと感じるようになりました。

つまりは、サーバーの構成を KISS したいのです。

そこで OS を、至極シンプルな構成の CoreOS 社の ContainerLinux（旧CoreOS）に変えて、Docker で機能追加する方が良いのではと感じています。

これにより、OS 側で必要なライブラリを用意しなくても、サービス毎に Docker イメージ（or Dockerfile）を用意すれば開発も環境依存せずにドッカンドッカン作れるのでは、と。

理想のイメージとしては、Nginx-proxy を 80/443 ポートの窓口にして、各々のサービスのコンテナにクエリを渡して返すだけの API に特化した構成が良いと考えています。

    https://qithub.tk/<container name>/  → リクエスト内容が <container name> のコンテナに渡される

年末の年越しでできればと考えています。ご意見、ご要望お待ちしていまーす。

## 補足

実のところ Minecraft のサーバーを建てたいと思ったのですが、依存の検証やリカバリーを考えると Docker のコンテナで導入した方が楽じゃないかというところから始まっているのですが。

## TL;DR（結論 2020/01/20 現在）

- CoreOS や RancherOS もやめて、従来通りの CentOS に Docker という組み合わせにすることにしました。

----------------

- [x] 過去の Issues も検索しましたが該当するものはありませんでした。

**Comment by hidao80** [comment]
Docker採用案に👍

私も最近Vagrant使い始めたのですが、（Win10HomeでDockerするのは難しくて挫折しました…）仮想環境はアプリ相互に干渉せず、かつリストアが簡単なので支持します。

本当にやりたいことはbot作成+αなので、鯖缶に頭を悩ませることを減らせるなら減らして行く方向でいいと考えます。

**Comment by KEINOS** [comment]
【相談】

現在 OS を CoreOS、RancherOS と BargeOS で悩んでいます。

クラスタとかも組む予定はなく、シングル・サーバーで Docker 専用 OS であれば何でもいいのですが、、、

GitHub からの WebHook が届いたら、`git  pull origin master` されて、メインの docker-compose.yml が再構築される程度のシンプルな構成にしたいと考えています。

**以下の挙動を考えた場合、どの OS を使うのが楽**ですかね。

- １機能（サービス）１Dockerfile １リポジトリで完結。
    - 各サービス（コンテナ）は Expose でのポートの外部公開はしない
    - 各サービスは各々 80 ポートで待機
    - 基本的に docker.sock はマウントさせない

- メインの `docker-compose.yml` は、各サービスごとに git リポジトリをビルドするだけ

    下記は `my_service1` のコンテナからは `my_service2` に `http://my_service2/` でアクセスできる。

```yaml
version: "3"

volumes:
  data_qiita_items:

services:
  my_service1:
    build:
      context: https://github.com/Qithub-BOT/my_service1.git
    volumes:
      - "data_qiita_items:/data"
    container_name: my_service1
  my_service2:
    build:
      context: https://github.com/Qithub-BOT/my_service2.git
    volumes:
      - "data_qiita_items:/data"
    container_name: my_service2
```
 
- フロントのコンテナは nginx-proxy で、80/443 のみ Listen し、Docker 内のネットワーク内をリバース・プロクシる
    - `https://qithub.gq/<サービス名>/` のアクセスは nginx-proxy コンテナ経由で同じ Docker ネットワーク内の `http://<サービス名>/` に転送
